// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8E1UufMPXtfoz4rgm6dz6JCZR21DOQdU',
    appId: '1:55163426810:web:c686dc1928200a9286f643',
    messagingSenderId: '55163426810',
    projectId: 'homezes-flutter-app',
    authDomain: 'homezes-flutter-app.firebaseapp.com',
    storageBucket: 'homezes-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyfpCLPwK-JzHaV0TZdBns5RrFWG9x-oE',
    appId: '1:55163426810:android:5a17d48b34cee2b386f643',
    messagingSenderId: '55163426810',
    projectId: 'homezes-flutter-app',
    storageBucket: 'homezes-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1fAN9Czk6ymA0Gi1jmLuXMcmTh1BN2WM',
    appId: '1:55163426810:ios:9ff2c7674774f13186f643',
    messagingSenderId: '55163426810',
    projectId: 'homezes-flutter-app',
    storageBucket: 'homezes-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.homzesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1fAN9Czk6ymA0Gi1jmLuXMcmTh1BN2WM',
    appId: '1:55163426810:ios:9ff2c7674774f13186f643',
    messagingSenderId: '55163426810',
    projectId: 'homezes-flutter-app',
    storageBucket: 'homezes-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.homzesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8E1UufMPXtfoz4rgm6dz6JCZR21DOQdU',
    appId: '1:55163426810:web:6dcb0ec1b1c6201586f643',
    messagingSenderId: '55163426810',
    projectId: 'homezes-flutter-app',
    authDomain: 'homezes-flutter-app.firebaseapp.com',
    storageBucket: 'homezes-flutter-app.firebasestorage.app',
  );
}
